### ISSUE TITLE
Making the Server code run as Daemon

### ISSUE THREAD

**Issue by PeterBraganza** [cu-ecen-aeld/final-project-PeterBraganza#15]
DoD:
* Server code should be running after boot
* When client code run on client-side data should be transmitted over LAN

**Comment by Sona-Subair** [comment]
The  Lan setup was done and the server is running over startup. The issue was resolved with reference to following commit hashes:
[#1](https://github.com/cu-ecen-aeld/final-project-suryakanteti/commit/2e7094210b6f5b74f59e77076452bf954bb146fc)
[#2](https://github.com/cu-ecen-aeld/final-project-Sona-Subair/commit/99db24cae03f44d5abf970c1148b6b324f6bacfb)
